// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EARTHCALL_EARTHCALL_SCHEMA_H_
#define FLATBUFFERS_GENERATED_EARTHCALL_EARTHCALL_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Earthcall {
namespace Schema {

struct LawProperty;
struct LawPropertyBuilder;

struct LawComponent;
struct LawComponentBuilder;

struct Vec3;

struct Vec4;

struct PolyhedronData;
struct PolyhedronDataBuilder;

struct SdfNode;
struct SdfNodeBuilder;

struct Entity;
struct EntityBuilder;

struct SaveChunk;
struct SaveChunkBuilder;

struct GlobalState;
struct GlobalStateBuilder;

enum PropertyType : int8_t {
  PropertyType_Int = 0,
  PropertyType_Float = 1,
  PropertyType_String = 2,
  PropertyType_Binary = 3,
  PropertyType_Bool = 4,
  PropertyType_MIN = PropertyType_Int,
  PropertyType_MAX = PropertyType_Bool
};

inline const PropertyType (&EnumValuesPropertyType())[5] {
  static const PropertyType values[] = {
    PropertyType_Int,
    PropertyType_Float,
    PropertyType_String,
    PropertyType_Binary,
    PropertyType_Bool
  };
  return values;
}

inline const char * const *EnumNamesPropertyType() {
  static const char * const names[6] = {
    "Int",
    "Float",
    "String",
    "Binary",
    "Bool",
    nullptr
  };
  return names;
}

inline const char *EnumNamePropertyType(PropertyType e) {
  if (::flatbuffers::IsOutRange(e, PropertyType_Int, PropertyType_Bool)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPropertyType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

struct LawProperty FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LawPropertyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_TYPE = 6,
    VT_VAL_INT = 8,
    VT_VAL_FLOAT = 10,
    VT_VAL_STRING = 12,
    VT_VAL_BINARY = 14,
    VT_VAL_BOOL = 16
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  Earthcall::Schema::PropertyType type() const {
    return static_cast<Earthcall::Schema::PropertyType>(GetField<int8_t>(VT_TYPE, 0));
  }
  int64_t val_int() const {
    return GetField<int64_t>(VT_VAL_INT, 0);
  }
  double val_float() const {
    return GetField<double>(VT_VAL_FLOAT, 0.0);
  }
  const ::flatbuffers::String *val_string() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VAL_STRING);
  }
  const ::flatbuffers::Vector<uint8_t> *val_binary() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VAL_BINARY);
  }
  bool val_bool() const {
    return GetField<uint8_t>(VT_VAL_BOOL, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int64_t>(verifier, VT_VAL_INT, 8) &&
           VerifyField<double>(verifier, VT_VAL_FLOAT, 8) &&
           VerifyOffset(verifier, VT_VAL_STRING) &&
           verifier.VerifyString(val_string()) &&
           VerifyOffset(verifier, VT_VAL_BINARY) &&
           verifier.VerifyVector(val_binary()) &&
           VerifyField<uint8_t>(verifier, VT_VAL_BOOL, 1) &&
           verifier.EndTable();
  }
};

struct LawPropertyBuilder {
  typedef LawProperty Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(LawProperty::VT_KEY, key);
  }
  void add_type(Earthcall::Schema::PropertyType type) {
    fbb_.AddElement<int8_t>(LawProperty::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_val_int(int64_t val_int) {
    fbb_.AddElement<int64_t>(LawProperty::VT_VAL_INT, val_int, 0);
  }
  void add_val_float(double val_float) {
    fbb_.AddElement<double>(LawProperty::VT_VAL_FLOAT, val_float, 0.0);
  }
  void add_val_string(::flatbuffers::Offset<::flatbuffers::String> val_string) {
    fbb_.AddOffset(LawProperty::VT_VAL_STRING, val_string);
  }
  void add_val_binary(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> val_binary) {
    fbb_.AddOffset(LawProperty::VT_VAL_BINARY, val_binary);
  }
  void add_val_bool(bool val_bool) {
    fbb_.AddElement<uint8_t>(LawProperty::VT_VAL_BOOL, static_cast<uint8_t>(val_bool), 0);
  }
  explicit LawPropertyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LawProperty> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LawProperty>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LawProperty> CreateLawProperty(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    Earthcall::Schema::PropertyType type = Earthcall::Schema::PropertyType_Int,
    int64_t val_int = 0,
    double val_float = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> val_string = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> val_binary = 0,
    bool val_bool = false) {
  LawPropertyBuilder builder_(_fbb);
  builder_.add_val_float(val_float);
  builder_.add_val_int(val_int);
  builder_.add_val_binary(val_binary);
  builder_.add_val_string(val_string);
  builder_.add_key(key);
  builder_.add_val_bool(val_bool);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LawProperty> CreateLawPropertyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    Earthcall::Schema::PropertyType type = Earthcall::Schema::PropertyType_Int,
    int64_t val_int = 0,
    double val_float = 0.0,
    const char *val_string = nullptr,
    const std::vector<uint8_t> *val_binary = nullptr,
    bool val_bool = false) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto val_string__ = val_string ? _fbb.CreateString(val_string) : 0;
  auto val_binary__ = val_binary ? _fbb.CreateVector<uint8_t>(*val_binary) : 0;
  return Earthcall::Schema::CreateLawProperty(
      _fbb,
      key__,
      type,
      val_int,
      val_float,
      val_string__,
      val_binary__,
      val_bool);
}

struct LawComponent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LawComponentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PROPERTIES = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>> *properties() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>> *>(VT_PROPERTIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_PROPERTIES) &&
           verifier.VerifyVector(properties()) &&
           verifier.VerifyVectorOfTables(properties()) &&
           verifier.EndTable();
  }
};

struct LawComponentBuilder {
  typedef LawComponent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(LawComponent::VT_NAME, name);
  }
  void add_properties(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>>> properties) {
    fbb_.AddOffset(LawComponent::VT_PROPERTIES, properties);
  }
  explicit LawComponentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LawComponent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LawComponent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LawComponent> CreateLawComponent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>>> properties = 0) {
  LawComponentBuilder builder_(_fbb);
  builder_.add_properties(properties);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LawComponent> CreateLawComponentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>> *properties = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto properties__ = properties ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>>(*properties) : 0;
  return Earthcall::Schema::CreateLawComponent(
      _fbb,
      name__,
      properties__);
}

struct PolyhedronData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PolyhedronDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_FACE_DATA = 6,
    VT_FACE_OFFSETS = 8
  };
  const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<int32_t> *face_data() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_FACE_DATA);
  }
  const ::flatbuffers::Vector<int32_t> *face_offsets() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_FACE_OFFSETS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_FACE_DATA) &&
           verifier.VerifyVector(face_data()) &&
           VerifyOffset(verifier, VT_FACE_OFFSETS) &&
           verifier.VerifyVector(face_offsets()) &&
           verifier.EndTable();
  }
};

struct PolyhedronDataBuilder {
  typedef PolyhedronData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> vertices) {
    fbb_.AddOffset(PolyhedronData::VT_VERTICES, vertices);
  }
  void add_face_data(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_data) {
    fbb_.AddOffset(PolyhedronData::VT_FACE_DATA, face_data);
  }
  void add_face_offsets(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_offsets) {
    fbb_.AddOffset(PolyhedronData::VT_FACE_OFFSETS, face_offsets);
  }
  explicit PolyhedronDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PolyhedronData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PolyhedronData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PolyhedronData> CreatePolyhedronData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_offsets = 0) {
  PolyhedronDataBuilder builder_(_fbb);
  builder_.add_face_offsets(face_offsets);
  builder_.add_face_data(face_data);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PolyhedronData> CreatePolyhedronDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Earthcall::Schema::Vec3> *vertices = nullptr,
    const std::vector<int32_t> *face_data = nullptr,
    const std::vector<int32_t> *face_offsets = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Earthcall::Schema::Vec3>(*vertices) : 0;
  auto face_data__ = face_data ? _fbb.CreateVector<int32_t>(*face_data) : 0;
  auto face_offsets__ = face_offsets ? _fbb.CreateVector<int32_t>(*face_offsets) : 0;
  return Earthcall::Schema::CreatePolyhedronData(
      _fbb,
      vertices__,
      face_data__,
      face_offsets__);
}

struct SdfNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SdfNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_OPERATION = 6,
    VT_TRANSFORM = 8,
    VT_PLANES = 10,
    VT_CHILDREN_INDICES = 12
  };
  int32_t type() const {
    return GetField<int32_t>(VT_TYPE, 0);
  }
  int32_t operation() const {
    return GetField<int32_t>(VT_OPERATION, 0);
  }
  const ::flatbuffers::Vector<float> *transform() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TRANSFORM);
  }
  const ::flatbuffers::Vector<const Earthcall::Schema::Vec4 *> *planes() const {
    return GetPointer<const ::flatbuffers::Vector<const Earthcall::Schema::Vec4 *> *>(VT_PLANES);
  }
  const ::flatbuffers::Vector<int32_t> *children_indices() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_CHILDREN_INDICES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_OPERATION, 4) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyVector(transform()) &&
           VerifyOffset(verifier, VT_PLANES) &&
           verifier.VerifyVector(planes()) &&
           VerifyOffset(verifier, VT_CHILDREN_INDICES) &&
           verifier.VerifyVector(children_indices()) &&
           verifier.EndTable();
  }
};

struct SdfNodeBuilder {
  typedef SdfNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(int32_t type) {
    fbb_.AddElement<int32_t>(SdfNode::VT_TYPE, type, 0);
  }
  void add_operation(int32_t operation) {
    fbb_.AddElement<int32_t>(SdfNode::VT_OPERATION, operation, 0);
  }
  void add_transform(::flatbuffers::Offset<::flatbuffers::Vector<float>> transform) {
    fbb_.AddOffset(SdfNode::VT_TRANSFORM, transform);
  }
  void add_planes(::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec4 *>> planes) {
    fbb_.AddOffset(SdfNode::VT_PLANES, planes);
  }
  void add_children_indices(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> children_indices) {
    fbb_.AddOffset(SdfNode::VT_CHILDREN_INDICES, children_indices);
  }
  explicit SdfNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SdfNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SdfNode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SdfNode> CreateSdfNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    int32_t operation = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> transform = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec4 *>> planes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> children_indices = 0) {
  SdfNodeBuilder builder_(_fbb);
  builder_.add_children_indices(children_indices);
  builder_.add_planes(planes);
  builder_.add_transform(transform);
  builder_.add_operation(operation);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SdfNode> CreateSdfNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    int32_t operation = 0,
    const std::vector<float> *transform = nullptr,
    const std::vector<Earthcall::Schema::Vec4> *planes = nullptr,
    const std::vector<int32_t> *children_indices = nullptr) {
  auto transform__ = transform ? _fbb.CreateVector<float>(*transform) : 0;
  auto planes__ = planes ? _fbb.CreateVectorOfStructs<Earthcall::Schema::Vec4>(*planes) : 0;
  auto children_indices__ = children_indices ? _fbb.CreateVector<int32_t>(*children_indices) : 0;
  return Earthcall::Schema::CreateSdfNode(
      _fbb,
      type,
      operation,
      transform__,
      planes__,
      children_indices__);
}

struct Entity FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_TRANSFORM = 8,
    VT_POLYHEDRON = 10,
    VT_SDF_NODES = 12,
    VT_LAWS = 14
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<float> *transform() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TRANSFORM);
  }
  const Earthcall::Schema::PolyhedronData *polyhedron() const {
    return GetPointer<const Earthcall::Schema::PolyhedronData *>(VT_POLYHEDRON);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>> *sdf_nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>> *>(VT_SDF_NODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>> *laws() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>> *>(VT_LAWS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyVector(transform()) &&
           VerifyOffset(verifier, VT_POLYHEDRON) &&
           verifier.VerifyTable(polyhedron()) &&
           VerifyOffset(verifier, VT_SDF_NODES) &&
           verifier.VerifyVector(sdf_nodes()) &&
           verifier.VerifyVectorOfTables(sdf_nodes()) &&
           VerifyOffset(verifier, VT_LAWS) &&
           verifier.VerifyVector(laws()) &&
           verifier.VerifyVectorOfTables(laws()) &&
           verifier.EndTable();
  }
};

struct EntityBuilder {
  typedef Entity Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Entity::VT_ID, id);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Entity::VT_NAME, name);
  }
  void add_transform(::flatbuffers::Offset<::flatbuffers::Vector<float>> transform) {
    fbb_.AddOffset(Entity::VT_TRANSFORM, transform);
  }
  void add_polyhedron(::flatbuffers::Offset<Earthcall::Schema::PolyhedronData> polyhedron) {
    fbb_.AddOffset(Entity::VT_POLYHEDRON, polyhedron);
  }
  void add_sdf_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>>> sdf_nodes) {
    fbb_.AddOffset(Entity::VT_SDF_NODES, sdf_nodes);
  }
  void add_laws(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>>> laws) {
    fbb_.AddOffset(Entity::VT_LAWS, laws);
  }
  explicit EntityBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Entity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Entity>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Entity> CreateEntity(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> transform = 0,
    ::flatbuffers::Offset<Earthcall::Schema::PolyhedronData> polyhedron = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>>> sdf_nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>>> laws = 0) {
  EntityBuilder builder_(_fbb);
  builder_.add_laws(laws);
  builder_.add_sdf_nodes(sdf_nodes);
  builder_.add_polyhedron(polyhedron);
  builder_.add_transform(transform);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Entity> CreateEntityDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const std::vector<float> *transform = nullptr,
    ::flatbuffers::Offset<Earthcall::Schema::PolyhedronData> polyhedron = 0,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>> *sdf_nodes = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>> *laws = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto transform__ = transform ? _fbb.CreateVector<float>(*transform) : 0;
  auto sdf_nodes__ = sdf_nodes ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>>(*sdf_nodes) : 0;
  auto laws__ = laws ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>>(*laws) : 0;
  return Earthcall::Schema::CreateEntity(
      _fbb,
      id__,
      name__,
      transform__,
      polyhedron,
      sdf_nodes__,
      laws__);
}

struct SaveChunk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SaveChunkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHUNK_ID = 4,
    VT_ENTITIES = 6
  };
  const ::flatbuffers::String *chunk_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHUNK_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>> *entities() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>> *>(VT_ENTITIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CHUNK_ID) &&
           verifier.VerifyString(chunk_id()) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.VerifyVectorOfTables(entities()) &&
           verifier.EndTable();
  }
};

struct SaveChunkBuilder {
  typedef SaveChunk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_chunk_id(::flatbuffers::Offset<::flatbuffers::String> chunk_id) {
    fbb_.AddOffset(SaveChunk::VT_CHUNK_ID, chunk_id);
  }
  void add_entities(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>>> entities) {
    fbb_.AddOffset(SaveChunk::VT_ENTITIES, entities);
  }
  explicit SaveChunkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SaveChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SaveChunk>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SaveChunk> CreateSaveChunk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> chunk_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>>> entities = 0) {
  SaveChunkBuilder builder_(_fbb);
  builder_.add_entities(entities);
  builder_.add_chunk_id(chunk_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SaveChunk> CreateSaveChunkDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *chunk_id = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::Entity>> *entities = nullptr) {
  auto chunk_id__ = chunk_id ? _fbb.CreateString(chunk_id) : 0;
  auto entities__ = entities ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::Entity>>(*entities) : 0;
  return Earthcall::Schema::CreateSaveChunk(
      _fbb,
      chunk_id__,
      entities__);
}

struct GlobalState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GlobalStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLD_NAME = 4,
    VT_TIMESTAMP = 6,
    VT_ACTIVE_LAWS = 8,
    VT_CHUNKS = 10
  };
  const ::flatbuffers::String *world_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WORLD_NAME);
  }
  const ::flatbuffers::String *timestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMESTAMP);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *active_laws() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ACTIVE_LAWS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *chunks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CHUNKS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORLD_NAME) &&
           verifier.VerifyString(world_name()) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyString(timestamp()) &&
           VerifyOffset(verifier, VT_ACTIVE_LAWS) &&
           verifier.VerifyVector(active_laws()) &&
           verifier.VerifyVectorOfStrings(active_laws()) &&
           VerifyOffset(verifier, VT_CHUNKS) &&
           verifier.VerifyVector(chunks()) &&
           verifier.VerifyVectorOfStrings(chunks()) &&
           verifier.EndTable();
  }
};

struct GlobalStateBuilder {
  typedef GlobalState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_world_name(::flatbuffers::Offset<::flatbuffers::String> world_name) {
    fbb_.AddOffset(GlobalState::VT_WORLD_NAME, world_name);
  }
  void add_timestamp(::flatbuffers::Offset<::flatbuffers::String> timestamp) {
    fbb_.AddOffset(GlobalState::VT_TIMESTAMP, timestamp);
  }
  void add_active_laws(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> active_laws) {
    fbb_.AddOffset(GlobalState::VT_ACTIVE_LAWS, active_laws);
  }
  void add_chunks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> chunks) {
    fbb_.AddOffset(GlobalState::VT_CHUNKS, chunks);
  }
  explicit GlobalStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GlobalState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GlobalState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GlobalState> CreateGlobalState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> world_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> active_laws = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> chunks = 0) {
  GlobalStateBuilder builder_(_fbb);
  builder_.add_chunks(chunks);
  builder_.add_active_laws(active_laws);
  builder_.add_timestamp(timestamp);
  builder_.add_world_name(world_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GlobalState> CreateGlobalStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *world_name = nullptr,
    const char *timestamp = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *active_laws = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *chunks = nullptr) {
  auto world_name__ = world_name ? _fbb.CreateString(world_name) : 0;
  auto timestamp__ = timestamp ? _fbb.CreateString(timestamp) : 0;
  auto active_laws__ = active_laws ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*active_laws) : 0;
  auto chunks__ = chunks ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*chunks) : 0;
  return Earthcall::Schema::CreateGlobalState(
      _fbb,
      world_name__,
      timestamp__,
      active_laws__,
      chunks__);
}

inline const Earthcall::Schema::SaveChunk *GetSaveChunk(const void *buf) {
  return ::flatbuffers::GetRoot<Earthcall::Schema::SaveChunk>(buf);
}

inline const Earthcall::Schema::SaveChunk *GetSizePrefixedSaveChunk(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Earthcall::Schema::SaveChunk>(buf);
}

template <bool B = false>
inline bool VerifySaveChunkBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Earthcall::Schema::SaveChunk>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedSaveChunkBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Earthcall::Schema::SaveChunk>(nullptr);
}

inline void FinishSaveChunkBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Earthcall::Schema::SaveChunk> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSaveChunkBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Earthcall::Schema::SaveChunk> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Schema
}  // namespace Earthcall

#endif  // FLATBUFFERS_GENERATED_EARTHCALL_EARTHCALL_SCHEMA_H_
