// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EARTHCALL_EARTHCALL_SCHEMA_H_
#define FLATBUFFERS_GENERATED_EARTHCALL_EARTHCALL_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Earthcall {
namespace Schema {

struct LawProperty;
struct LawPropertyBuilder;

struct LawComponent;
struct LawComponentBuilder;

struct Vec3;

struct Vec4;

struct PolyhedronData;
struct PolyhedronDataBuilder;

struct BezierPatch;
struct BezierPatchBuilder;

struct FaceTexture;
struct FaceTextureBuilder;

struct SmoothSurfaceData;
struct SmoothSurfaceDataBuilder;

struct SdfNode;
struct SdfNodeBuilder;

struct FieldData;
struct FieldDataBuilder;

struct Entity;
struct EntityBuilder;

struct SaveChunk;
struct SaveChunkBuilder;

struct GlobalState;
struct GlobalStateBuilder;

enum PropertyType : int8_t {
  PropertyType_Int = 0,
  PropertyType_Float = 1,
  PropertyType_String = 2,
  PropertyType_Binary = 3,
  PropertyType_Bool = 4,
  PropertyType_MIN = PropertyType_Int,
  PropertyType_MAX = PropertyType_Bool
};

inline const PropertyType (&EnumValuesPropertyType())[5] {
  static const PropertyType values[] = {
    PropertyType_Int,
    PropertyType_Float,
    PropertyType_String,
    PropertyType_Binary,
    PropertyType_Bool
  };
  return values;
}

inline const char * const *EnumNamesPropertyType() {
  static const char * const names[6] = {
    "Int",
    "Float",
    "String",
    "Binary",
    "Bool",
    nullptr
  };
  return names;
}

inline const char *EnumNamePropertyType(PropertyType e) {
  if (::flatbuffers::IsOutRange(e, PropertyType_Int, PropertyType_Bool)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPropertyType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

struct LawProperty FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LawPropertyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_TYPE = 6,
    VT_VAL_INT = 8,
    VT_VAL_FLOAT = 10,
    VT_VAL_STRING = 12,
    VT_VAL_BINARY = 14,
    VT_VAL_BOOL = 16
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  Earthcall::Schema::PropertyType type() const {
    return static_cast<Earthcall::Schema::PropertyType>(GetField<int8_t>(VT_TYPE, 0));
  }
  int64_t val_int() const {
    return GetField<int64_t>(VT_VAL_INT, 0);
  }
  double val_float() const {
    return GetField<double>(VT_VAL_FLOAT, 0.0);
  }
  const ::flatbuffers::String *val_string() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VAL_STRING);
  }
  const ::flatbuffers::Vector<uint8_t> *val_binary() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VAL_BINARY);
  }
  bool val_bool() const {
    return GetField<uint8_t>(VT_VAL_BOOL, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int64_t>(verifier, VT_VAL_INT, 8) &&
           VerifyField<double>(verifier, VT_VAL_FLOAT, 8) &&
           VerifyOffset(verifier, VT_VAL_STRING) &&
           verifier.VerifyString(val_string()) &&
           VerifyOffset(verifier, VT_VAL_BINARY) &&
           verifier.VerifyVector(val_binary()) &&
           VerifyField<uint8_t>(verifier, VT_VAL_BOOL, 1) &&
           verifier.EndTable();
  }
};

struct LawPropertyBuilder {
  typedef LawProperty Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(LawProperty::VT_KEY, key);
  }
  void add_type(Earthcall::Schema::PropertyType type) {
    fbb_.AddElement<int8_t>(LawProperty::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_val_int(int64_t val_int) {
    fbb_.AddElement<int64_t>(LawProperty::VT_VAL_INT, val_int, 0);
  }
  void add_val_float(double val_float) {
    fbb_.AddElement<double>(LawProperty::VT_VAL_FLOAT, val_float, 0.0);
  }
  void add_val_string(::flatbuffers::Offset<::flatbuffers::String> val_string) {
    fbb_.AddOffset(LawProperty::VT_VAL_STRING, val_string);
  }
  void add_val_binary(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> val_binary) {
    fbb_.AddOffset(LawProperty::VT_VAL_BINARY, val_binary);
  }
  void add_val_bool(bool val_bool) {
    fbb_.AddElement<uint8_t>(LawProperty::VT_VAL_BOOL, static_cast<uint8_t>(val_bool), 0);
  }
  explicit LawPropertyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LawProperty> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LawProperty>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LawProperty> CreateLawProperty(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    Earthcall::Schema::PropertyType type = Earthcall::Schema::PropertyType_Int,
    int64_t val_int = 0,
    double val_float = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> val_string = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> val_binary = 0,
    bool val_bool = false) {
  LawPropertyBuilder builder_(_fbb);
  builder_.add_val_float(val_float);
  builder_.add_val_int(val_int);
  builder_.add_val_binary(val_binary);
  builder_.add_val_string(val_string);
  builder_.add_key(key);
  builder_.add_val_bool(val_bool);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LawProperty> CreateLawPropertyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    Earthcall::Schema::PropertyType type = Earthcall::Schema::PropertyType_Int,
    int64_t val_int = 0,
    double val_float = 0.0,
    const char *val_string = nullptr,
    const std::vector<uint8_t> *val_binary = nullptr,
    bool val_bool = false) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto val_string__ = val_string ? _fbb.CreateString(val_string) : 0;
  auto val_binary__ = val_binary ? _fbb.CreateVector<uint8_t>(*val_binary) : 0;
  return Earthcall::Schema::CreateLawProperty(
      _fbb,
      key__,
      type,
      val_int,
      val_float,
      val_string__,
      val_binary__,
      val_bool);
}

struct LawComponent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LawComponentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PROPERTIES = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>> *properties() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>> *>(VT_PROPERTIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_PROPERTIES) &&
           verifier.VerifyVector(properties()) &&
           verifier.VerifyVectorOfTables(properties()) &&
           verifier.EndTable();
  }
};

struct LawComponentBuilder {
  typedef LawComponent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(LawComponent::VT_NAME, name);
  }
  void add_properties(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>>> properties) {
    fbb_.AddOffset(LawComponent::VT_PROPERTIES, properties);
  }
  explicit LawComponentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LawComponent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LawComponent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LawComponent> CreateLawComponent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>>> properties = 0) {
  LawComponentBuilder builder_(_fbb);
  builder_.add_properties(properties);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LawComponent> CreateLawComponentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>> *properties = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto properties__ = properties ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::LawProperty>>(*properties) : 0;
  return Earthcall::Schema::CreateLawComponent(
      _fbb,
      name__,
      properties__);
}

struct PolyhedronData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PolyhedronDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_FACE_DATA = 6,
    VT_FACE_OFFSETS = 8
  };
  const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<int32_t> *face_data() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_FACE_DATA);
  }
  const ::flatbuffers::Vector<int32_t> *face_offsets() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_FACE_OFFSETS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_FACE_DATA) &&
           verifier.VerifyVector(face_data()) &&
           VerifyOffset(verifier, VT_FACE_OFFSETS) &&
           verifier.VerifyVector(face_offsets()) &&
           verifier.EndTable();
  }
};

struct PolyhedronDataBuilder {
  typedef PolyhedronData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> vertices) {
    fbb_.AddOffset(PolyhedronData::VT_VERTICES, vertices);
  }
  void add_face_data(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_data) {
    fbb_.AddOffset(PolyhedronData::VT_FACE_DATA, face_data);
  }
  void add_face_offsets(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_offsets) {
    fbb_.AddOffset(PolyhedronData::VT_FACE_OFFSETS, face_offsets);
  }
  explicit PolyhedronDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PolyhedronData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PolyhedronData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PolyhedronData> CreatePolyhedronData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> face_offsets = 0) {
  PolyhedronDataBuilder builder_(_fbb);
  builder_.add_face_offsets(face_offsets);
  builder_.add_face_data(face_data);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PolyhedronData> CreatePolyhedronDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Earthcall::Schema::Vec3> *vertices = nullptr,
    const std::vector<int32_t> *face_data = nullptr,
    const std::vector<int32_t> *face_offsets = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Earthcall::Schema::Vec3>(*vertices) : 0;
  auto face_data__ = face_data ? _fbb.CreateVector<int32_t>(*face_data) : 0;
  auto face_offsets__ = face_offsets ? _fbb.CreateVector<int32_t>(*face_offsets) : 0;
  return Earthcall::Schema::CreatePolyhedronData(
      _fbb,
      vertices__,
      face_data__,
      face_offsets__);
}

struct BezierPatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BezierPatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DU = 4,
    VT_DV = 6,
    VT_CTRL = 8
  };
  int32_t du() const {
    return GetField<int32_t>(VT_DU, 0);
  }
  int32_t dv() const {
    return GetField<int32_t>(VT_DV, 0);
  }
  const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *ctrl() const {
    return GetPointer<const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *>(VT_CTRL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_DU, 4) &&
           VerifyField<int32_t>(verifier, VT_DV, 4) &&
           VerifyOffset(verifier, VT_CTRL) &&
           verifier.VerifyVector(ctrl()) &&
           verifier.EndTable();
  }
};

struct BezierPatchBuilder {
  typedef BezierPatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_du(int32_t du) {
    fbb_.AddElement<int32_t>(BezierPatch::VT_DU, du, 0);
  }
  void add_dv(int32_t dv) {
    fbb_.AddElement<int32_t>(BezierPatch::VT_DV, dv, 0);
  }
  void add_ctrl(::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> ctrl) {
    fbb_.AddOffset(BezierPatch::VT_CTRL, ctrl);
  }
  explicit BezierPatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BezierPatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BezierPatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BezierPatch> CreateBezierPatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t du = 0,
    int32_t dv = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> ctrl = 0) {
  BezierPatchBuilder builder_(_fbb);
  builder_.add_ctrl(ctrl);
  builder_.add_dv(dv);
  builder_.add_du(du);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BezierPatch> CreateBezierPatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t du = 0,
    int32_t dv = 0,
    const std::vector<Earthcall::Schema::Vec3> *ctrl = nullptr) {
  auto ctrl__ = ctrl ? _fbb.CreateVectorOfStructs<Earthcall::Schema::Vec3>(*ctrl) : 0;
  return Earthcall::Schema::CreateBezierPatch(
      _fbb,
      du,
      dv,
      ctrl__);
}

struct FaceTexture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FaceTextureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FACE_INDEX = 4,
    VT_SIZE = 6,
    VT_PIXELS = 8
  };
  int32_t face_index() const {
    return GetField<int32_t>(VT_FACE_INDEX, 0);
  }
  int32_t size() const {
    return GetField<int32_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *pixels() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PIXELS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_FACE_INDEX, 4) &&
           VerifyField<int32_t>(verifier, VT_SIZE, 4) &&
           VerifyOffset(verifier, VT_PIXELS) &&
           verifier.VerifyVector(pixels()) &&
           verifier.EndTable();
  }
};

struct FaceTextureBuilder {
  typedef FaceTexture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_face_index(int32_t face_index) {
    fbb_.AddElement<int32_t>(FaceTexture::VT_FACE_INDEX, face_index, 0);
  }
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(FaceTexture::VT_SIZE, size, 0);
  }
  void add_pixels(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pixels) {
    fbb_.AddOffset(FaceTexture::VT_PIXELS, pixels);
  }
  explicit FaceTextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FaceTexture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FaceTexture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FaceTexture> CreateFaceTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t face_index = 0,
    int32_t size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pixels = 0) {
  FaceTextureBuilder builder_(_fbb);
  builder_.add_pixels(pixels);
  builder_.add_size(size);
  builder_.add_face_index(face_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FaceTexture> CreateFaceTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t face_index = 0,
    int32_t size = 0,
    const std::vector<uint8_t> *pixels = nullptr) {
  auto pixels__ = pixels ? _fbb.CreateVector<uint8_t>(*pixels) : 0;
  return Earthcall::Schema::CreateFaceTexture(
      _fbb,
      face_index,
      size,
      pixels__);
}

struct SmoothSurfaceData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SmoothSurfaceDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLOSED = 4,
    VT_ORIENTABLE = 6,
    VT_HAS_BOUNDARY = 8,
    VT_IS_VOLUME = 10,
    VT_MODEL = 12,
    VT_QUADRIC_MATRIX = 14,
    VT_QUADRIC_FORM = 16,
    VT_PARAMETRIC_KIND = 18,
    VT_AXES = 20,
    VT_Z_TRIM_MIN = 22,
    VT_Z_TRIM_MAX = 24,
    VT_PARAMS = 26
  };
  bool closed() const {
    return GetField<uint8_t>(VT_CLOSED, 1) != 0;
  }
  bool orientable() const {
    return GetField<uint8_t>(VT_ORIENTABLE, 1) != 0;
  }
  bool has_boundary() const {
    return GetField<uint8_t>(VT_HAS_BOUNDARY, 0) != 0;
  }
  bool is_volume() const {
    return GetField<uint8_t>(VT_IS_VOLUME, 0) != 0;
  }
  int32_t model() const {
    return GetField<int32_t>(VT_MODEL, 0);
  }
  const ::flatbuffers::Vector<float> *quadric_matrix() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_QUADRIC_MATRIX);
  }
  int32_t quadric_form() const {
    return GetField<int32_t>(VT_QUADRIC_FORM, 0);
  }
  int32_t parametric_kind() const {
    return GetField<int32_t>(VT_PARAMETRIC_KIND, 0);
  }
  const Earthcall::Schema::Vec3 *axes() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_AXES);
  }
  float z_trim_min() const {
    return GetField<float>(VT_Z_TRIM_MIN, -0.5f);
  }
  float z_trim_max() const {
    return GetField<float>(VT_Z_TRIM_MAX, 0.5f);
  }
  const ::flatbuffers::Vector<float> *params() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_PARAMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CLOSED, 1) &&
           VerifyField<uint8_t>(verifier, VT_ORIENTABLE, 1) &&
           VerifyField<uint8_t>(verifier, VT_HAS_BOUNDARY, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_VOLUME, 1) &&
           VerifyField<int32_t>(verifier, VT_MODEL, 4) &&
           VerifyOffset(verifier, VT_QUADRIC_MATRIX) &&
           verifier.VerifyVector(quadric_matrix()) &&
           VerifyField<int32_t>(verifier, VT_QUADRIC_FORM, 4) &&
           VerifyField<int32_t>(verifier, VT_PARAMETRIC_KIND, 4) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_AXES, 4) &&
           VerifyField<float>(verifier, VT_Z_TRIM_MIN, 4) &&
           VerifyField<float>(verifier, VT_Z_TRIM_MAX, 4) &&
           VerifyOffset(verifier, VT_PARAMS) &&
           verifier.VerifyVector(params()) &&
           verifier.EndTable();
  }
};

struct SmoothSurfaceDataBuilder {
  typedef SmoothSurfaceData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_closed(bool closed) {
    fbb_.AddElement<uint8_t>(SmoothSurfaceData::VT_CLOSED, static_cast<uint8_t>(closed), 1);
  }
  void add_orientable(bool orientable) {
    fbb_.AddElement<uint8_t>(SmoothSurfaceData::VT_ORIENTABLE, static_cast<uint8_t>(orientable), 1);
  }
  void add_has_boundary(bool has_boundary) {
    fbb_.AddElement<uint8_t>(SmoothSurfaceData::VT_HAS_BOUNDARY, static_cast<uint8_t>(has_boundary), 0);
  }
  void add_is_volume(bool is_volume) {
    fbb_.AddElement<uint8_t>(SmoothSurfaceData::VT_IS_VOLUME, static_cast<uint8_t>(is_volume), 0);
  }
  void add_model(int32_t model) {
    fbb_.AddElement<int32_t>(SmoothSurfaceData::VT_MODEL, model, 0);
  }
  void add_quadric_matrix(::flatbuffers::Offset<::flatbuffers::Vector<float>> quadric_matrix) {
    fbb_.AddOffset(SmoothSurfaceData::VT_QUADRIC_MATRIX, quadric_matrix);
  }
  void add_quadric_form(int32_t quadric_form) {
    fbb_.AddElement<int32_t>(SmoothSurfaceData::VT_QUADRIC_FORM, quadric_form, 0);
  }
  void add_parametric_kind(int32_t parametric_kind) {
    fbb_.AddElement<int32_t>(SmoothSurfaceData::VT_PARAMETRIC_KIND, parametric_kind, 0);
  }
  void add_axes(const Earthcall::Schema::Vec3 *axes) {
    fbb_.AddStruct(SmoothSurfaceData::VT_AXES, axes);
  }
  void add_z_trim_min(float z_trim_min) {
    fbb_.AddElement<float>(SmoothSurfaceData::VT_Z_TRIM_MIN, z_trim_min, -0.5f);
  }
  void add_z_trim_max(float z_trim_max) {
    fbb_.AddElement<float>(SmoothSurfaceData::VT_Z_TRIM_MAX, z_trim_max, 0.5f);
  }
  void add_params(::flatbuffers::Offset<::flatbuffers::Vector<float>> params) {
    fbb_.AddOffset(SmoothSurfaceData::VT_PARAMS, params);
  }
  explicit SmoothSurfaceDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SmoothSurfaceData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SmoothSurfaceData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SmoothSurfaceData> CreateSmoothSurfaceData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool closed = true,
    bool orientable = true,
    bool has_boundary = false,
    bool is_volume = false,
    int32_t model = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> quadric_matrix = 0,
    int32_t quadric_form = 0,
    int32_t parametric_kind = 0,
    const Earthcall::Schema::Vec3 *axes = nullptr,
    float z_trim_min = -0.5f,
    float z_trim_max = 0.5f,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> params = 0) {
  SmoothSurfaceDataBuilder builder_(_fbb);
  builder_.add_params(params);
  builder_.add_z_trim_max(z_trim_max);
  builder_.add_z_trim_min(z_trim_min);
  builder_.add_axes(axes);
  builder_.add_parametric_kind(parametric_kind);
  builder_.add_quadric_form(quadric_form);
  builder_.add_quadric_matrix(quadric_matrix);
  builder_.add_model(model);
  builder_.add_is_volume(is_volume);
  builder_.add_has_boundary(has_boundary);
  builder_.add_orientable(orientable);
  builder_.add_closed(closed);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SmoothSurfaceData> CreateSmoothSurfaceDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool closed = true,
    bool orientable = true,
    bool has_boundary = false,
    bool is_volume = false,
    int32_t model = 0,
    const std::vector<float> *quadric_matrix = nullptr,
    int32_t quadric_form = 0,
    int32_t parametric_kind = 0,
    const Earthcall::Schema::Vec3 *axes = nullptr,
    float z_trim_min = -0.5f,
    float z_trim_max = 0.5f,
    const std::vector<float> *params = nullptr) {
  auto quadric_matrix__ = quadric_matrix ? _fbb.CreateVector<float>(*quadric_matrix) : 0;
  auto params__ = params ? _fbb.CreateVector<float>(*params) : 0;
  return Earthcall::Schema::CreateSmoothSurfaceData(
      _fbb,
      closed,
      orientable,
      has_boundary,
      is_volume,
      model,
      quadric_matrix__,
      quadric_form,
      parametric_kind,
      axes,
      z_trim_min,
      z_trim_max,
      params__);
}

struct SdfNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SdfNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_OPERATION = 6,
    VT_TRANSFORM = 8,
    VT_PLANES = 10,
    VT_CHILDREN_INDICES = 12,
    VT_DIMS = 14,
    VT_OFFSET = 16,
    VT_P0 = 18,
    VT_P1 = 20,
    VT_T = 22,
    VT_EXPR = 24
  };
  int32_t type() const {
    return GetField<int32_t>(VT_TYPE, 0);
  }
  int32_t operation() const {
    return GetField<int32_t>(VT_OPERATION, 0);
  }
  const ::flatbuffers::Vector<float> *transform() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TRANSFORM);
  }
  const ::flatbuffers::Vector<const Earthcall::Schema::Vec4 *> *planes() const {
    return GetPointer<const ::flatbuffers::Vector<const Earthcall::Schema::Vec4 *> *>(VT_PLANES);
  }
  const ::flatbuffers::Vector<int32_t> *children_indices() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_CHILDREN_INDICES);
  }
  const Earthcall::Schema::Vec3 *dims() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_DIMS);
  }
  const Earthcall::Schema::Vec3 *offset() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_OFFSET);
  }
  float p0() const {
    return GetField<float>(VT_P0, 0.0f);
  }
  float p1() const {
    return GetField<float>(VT_P1, 0.0f);
  }
  float t() const {
    return GetField<float>(VT_T, 0.0f);
  }
  const ::flatbuffers::String *expr() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXPR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_OPERATION, 4) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyVector(transform()) &&
           VerifyOffset(verifier, VT_PLANES) &&
           verifier.VerifyVector(planes()) &&
           VerifyOffset(verifier, VT_CHILDREN_INDICES) &&
           verifier.VerifyVector(children_indices()) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_DIMS, 4) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_OFFSET, 4) &&
           VerifyField<float>(verifier, VT_P0, 4) &&
           VerifyField<float>(verifier, VT_P1, 4) &&
           VerifyField<float>(verifier, VT_T, 4) &&
           VerifyOffset(verifier, VT_EXPR) &&
           verifier.VerifyString(expr()) &&
           verifier.EndTable();
  }
};

struct SdfNodeBuilder {
  typedef SdfNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(int32_t type) {
    fbb_.AddElement<int32_t>(SdfNode::VT_TYPE, type, 0);
  }
  void add_operation(int32_t operation) {
    fbb_.AddElement<int32_t>(SdfNode::VT_OPERATION, operation, 0);
  }
  void add_transform(::flatbuffers::Offset<::flatbuffers::Vector<float>> transform) {
    fbb_.AddOffset(SdfNode::VT_TRANSFORM, transform);
  }
  void add_planes(::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec4 *>> planes) {
    fbb_.AddOffset(SdfNode::VT_PLANES, planes);
  }
  void add_children_indices(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> children_indices) {
    fbb_.AddOffset(SdfNode::VT_CHILDREN_INDICES, children_indices);
  }
  void add_dims(const Earthcall::Schema::Vec3 *dims) {
    fbb_.AddStruct(SdfNode::VT_DIMS, dims);
  }
  void add_offset(const Earthcall::Schema::Vec3 *offset) {
    fbb_.AddStruct(SdfNode::VT_OFFSET, offset);
  }
  void add_p0(float p0) {
    fbb_.AddElement<float>(SdfNode::VT_P0, p0, 0.0f);
  }
  void add_p1(float p1) {
    fbb_.AddElement<float>(SdfNode::VT_P1, p1, 0.0f);
  }
  void add_t(float t) {
    fbb_.AddElement<float>(SdfNode::VT_T, t, 0.0f);
  }
  void add_expr(::flatbuffers::Offset<::flatbuffers::String> expr) {
    fbb_.AddOffset(SdfNode::VT_EXPR, expr);
  }
  explicit SdfNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SdfNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SdfNode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SdfNode> CreateSdfNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    int32_t operation = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> transform = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec4 *>> planes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> children_indices = 0,
    const Earthcall::Schema::Vec3 *dims = nullptr,
    const Earthcall::Schema::Vec3 *offset = nullptr,
    float p0 = 0.0f,
    float p1 = 0.0f,
    float t = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> expr = 0) {
  SdfNodeBuilder builder_(_fbb);
  builder_.add_expr(expr);
  builder_.add_t(t);
  builder_.add_p1(p1);
  builder_.add_p0(p0);
  builder_.add_offset(offset);
  builder_.add_dims(dims);
  builder_.add_children_indices(children_indices);
  builder_.add_planes(planes);
  builder_.add_transform(transform);
  builder_.add_operation(operation);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SdfNode> CreateSdfNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    int32_t operation = 0,
    const std::vector<float> *transform = nullptr,
    const std::vector<Earthcall::Schema::Vec4> *planes = nullptr,
    const std::vector<int32_t> *children_indices = nullptr,
    const Earthcall::Schema::Vec3 *dims = nullptr,
    const Earthcall::Schema::Vec3 *offset = nullptr,
    float p0 = 0.0f,
    float p1 = 0.0f,
    float t = 0.0f,
    const char *expr = nullptr) {
  auto transform__ = transform ? _fbb.CreateVector<float>(*transform) : 0;
  auto planes__ = planes ? _fbb.CreateVectorOfStructs<Earthcall::Schema::Vec4>(*planes) : 0;
  auto children_indices__ = children_indices ? _fbb.CreateVector<int32_t>(*children_indices) : 0;
  auto expr__ = expr ? _fbb.CreateString(expr) : 0;
  return Earthcall::Schema::CreateSdfNode(
      _fbb,
      type,
      operation,
      transform__,
      planes__,
      children_indices__,
      dims,
      offset,
      p0,
      p1,
      t,
      expr__);
}

struct FieldData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FieldDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EXTENT = 4,
    VT_ROOT_NODE = 6
  };
  const Earthcall::Schema::Vec3 *extent() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_EXTENT);
  }
  const Earthcall::Schema::SdfNode *root_node() const {
    return GetPointer<const Earthcall::Schema::SdfNode *>(VT_ROOT_NODE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_EXTENT, 4) &&
           VerifyOffset(verifier, VT_ROOT_NODE) &&
           verifier.VerifyTable(root_node()) &&
           verifier.EndTable();
  }
};

struct FieldDataBuilder {
  typedef FieldData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_extent(const Earthcall::Schema::Vec3 *extent) {
    fbb_.AddStruct(FieldData::VT_EXTENT, extent);
  }
  void add_root_node(::flatbuffers::Offset<Earthcall::Schema::SdfNode> root_node) {
    fbb_.AddOffset(FieldData::VT_ROOT_NODE, root_node);
  }
  explicit FieldDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FieldData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FieldData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FieldData> CreateFieldData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Earthcall::Schema::Vec3 *extent = nullptr,
    ::flatbuffers::Offset<Earthcall::Schema::SdfNode> root_node = 0) {
  FieldDataBuilder builder_(_fbb);
  builder_.add_root_node(root_node);
  builder_.add_extent(extent);
  return builder_.Finish();
}

struct Entity FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_TRANSFORM = 8,
    VT_POLYHEDRON = 10,
    VT_PATCH = 12,
    VT_SMOOTH_DATA = 14,
    VT_FIELD = 16,
    VT_FACE_TEXTURES = 18,
    VT_FACE_COLORS = 20,
    VT_SDF_NODES = 22,
    VT_LAWS = 24,
    VT_MATERIAL_ID = 26,
    VT_CENTER = 28,
    VT_AUTHORITATIVE_AXIS = 30,
    VT_TARGET_ROTATION = 32,
    VT_ROTATION_RESPONSIVENESS = 34
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<float> *transform() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TRANSFORM);
  }
  const Earthcall::Schema::PolyhedronData *polyhedron() const {
    return GetPointer<const Earthcall::Schema::PolyhedronData *>(VT_POLYHEDRON);
  }
  const Earthcall::Schema::BezierPatch *patch() const {
    return GetPointer<const Earthcall::Schema::BezierPatch *>(VT_PATCH);
  }
  const Earthcall::Schema::SmoothSurfaceData *smooth_data() const {
    return GetPointer<const Earthcall::Schema::SmoothSurfaceData *>(VT_SMOOTH_DATA);
  }
  const Earthcall::Schema::FieldData *field() const {
    return GetPointer<const Earthcall::Schema::FieldData *>(VT_FIELD);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::FaceTexture>> *face_textures() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::FaceTexture>> *>(VT_FACE_TEXTURES);
  }
  const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *face_colors() const {
    return GetPointer<const ::flatbuffers::Vector<const Earthcall::Schema::Vec3 *> *>(VT_FACE_COLORS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>> *sdf_nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>> *>(VT_SDF_NODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>> *laws() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>> *>(VT_LAWS);
  }
  const ::flatbuffers::String *material_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL_ID);
  }
  const Earthcall::Schema::Vec3 *center() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_CENTER);
  }
  const Earthcall::Schema::Vec3 *authoritative_axis() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_AUTHORITATIVE_AXIS);
  }
  const Earthcall::Schema::Vec3 *target_rotation() const {
    return GetStruct<const Earthcall::Schema::Vec3 *>(VT_TARGET_ROTATION);
  }
  float rotation_responsiveness() const {
    return GetField<float>(VT_ROTATION_RESPONSIVENESS, 1.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyVector(transform()) &&
           VerifyOffset(verifier, VT_POLYHEDRON) &&
           verifier.VerifyTable(polyhedron()) &&
           VerifyOffset(verifier, VT_PATCH) &&
           verifier.VerifyTable(patch()) &&
           VerifyOffset(verifier, VT_SMOOTH_DATA) &&
           verifier.VerifyTable(smooth_data()) &&
           VerifyOffset(verifier, VT_FIELD) &&
           verifier.VerifyTable(field()) &&
           VerifyOffset(verifier, VT_FACE_TEXTURES) &&
           verifier.VerifyVector(face_textures()) &&
           verifier.VerifyVectorOfTables(face_textures()) &&
           VerifyOffset(verifier, VT_FACE_COLORS) &&
           verifier.VerifyVector(face_colors()) &&
           VerifyOffset(verifier, VT_SDF_NODES) &&
           verifier.VerifyVector(sdf_nodes()) &&
           verifier.VerifyVectorOfTables(sdf_nodes()) &&
           VerifyOffset(verifier, VT_LAWS) &&
           verifier.VerifyVector(laws()) &&
           verifier.VerifyVectorOfTables(laws()) &&
           VerifyOffset(verifier, VT_MATERIAL_ID) &&
           verifier.VerifyString(material_id()) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_CENTER, 4) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_AUTHORITATIVE_AXIS, 4) &&
           VerifyField<Earthcall::Schema::Vec3>(verifier, VT_TARGET_ROTATION, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_RESPONSIVENESS, 4) &&
           verifier.EndTable();
  }
};

struct EntityBuilder {
  typedef Entity Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Entity::VT_ID, id);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Entity::VT_NAME, name);
  }
  void add_transform(::flatbuffers::Offset<::flatbuffers::Vector<float>> transform) {
    fbb_.AddOffset(Entity::VT_TRANSFORM, transform);
  }
  void add_polyhedron(::flatbuffers::Offset<Earthcall::Schema::PolyhedronData> polyhedron) {
    fbb_.AddOffset(Entity::VT_POLYHEDRON, polyhedron);
  }
  void add_patch(::flatbuffers::Offset<Earthcall::Schema::BezierPatch> patch) {
    fbb_.AddOffset(Entity::VT_PATCH, patch);
  }
  void add_smooth_data(::flatbuffers::Offset<Earthcall::Schema::SmoothSurfaceData> smooth_data) {
    fbb_.AddOffset(Entity::VT_SMOOTH_DATA, smooth_data);
  }
  void add_field(::flatbuffers::Offset<Earthcall::Schema::FieldData> field) {
    fbb_.AddOffset(Entity::VT_FIELD, field);
  }
  void add_face_textures(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::FaceTexture>>> face_textures) {
    fbb_.AddOffset(Entity::VT_FACE_TEXTURES, face_textures);
  }
  void add_face_colors(::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> face_colors) {
    fbb_.AddOffset(Entity::VT_FACE_COLORS, face_colors);
  }
  void add_sdf_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>>> sdf_nodes) {
    fbb_.AddOffset(Entity::VT_SDF_NODES, sdf_nodes);
  }
  void add_laws(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>>> laws) {
    fbb_.AddOffset(Entity::VT_LAWS, laws);
  }
  void add_material_id(::flatbuffers::Offset<::flatbuffers::String> material_id) {
    fbb_.AddOffset(Entity::VT_MATERIAL_ID, material_id);
  }
  void add_center(const Earthcall::Schema::Vec3 *center) {
    fbb_.AddStruct(Entity::VT_CENTER, center);
  }
  void add_authoritative_axis(const Earthcall::Schema::Vec3 *authoritative_axis) {
    fbb_.AddStruct(Entity::VT_AUTHORITATIVE_AXIS, authoritative_axis);
  }
  void add_target_rotation(const Earthcall::Schema::Vec3 *target_rotation) {
    fbb_.AddStruct(Entity::VT_TARGET_ROTATION, target_rotation);
  }
  void add_rotation_responsiveness(float rotation_responsiveness) {
    fbb_.AddElement<float>(Entity::VT_ROTATION_RESPONSIVENESS, rotation_responsiveness, 1.0f);
  }
  explicit EntityBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Entity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Entity>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Entity> CreateEntity(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> transform = 0,
    ::flatbuffers::Offset<Earthcall::Schema::PolyhedronData> polyhedron = 0,
    ::flatbuffers::Offset<Earthcall::Schema::BezierPatch> patch = 0,
    ::flatbuffers::Offset<Earthcall::Schema::SmoothSurfaceData> smooth_data = 0,
    ::flatbuffers::Offset<Earthcall::Schema::FieldData> field = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::FaceTexture>>> face_textures = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Earthcall::Schema::Vec3 *>> face_colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>>> sdf_nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>>> laws = 0,
    ::flatbuffers::Offset<::flatbuffers::String> material_id = 0,
    const Earthcall::Schema::Vec3 *center = nullptr,
    const Earthcall::Schema::Vec3 *authoritative_axis = nullptr,
    const Earthcall::Schema::Vec3 *target_rotation = nullptr,
    float rotation_responsiveness = 1.0f) {
  EntityBuilder builder_(_fbb);
  builder_.add_rotation_responsiveness(rotation_responsiveness);
  builder_.add_target_rotation(target_rotation);
  builder_.add_authoritative_axis(authoritative_axis);
  builder_.add_center(center);
  builder_.add_material_id(material_id);
  builder_.add_laws(laws);
  builder_.add_sdf_nodes(sdf_nodes);
  builder_.add_face_colors(face_colors);
  builder_.add_face_textures(face_textures);
  builder_.add_field(field);
  builder_.add_smooth_data(smooth_data);
  builder_.add_patch(patch);
  builder_.add_polyhedron(polyhedron);
  builder_.add_transform(transform);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Entity> CreateEntityDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const std::vector<float> *transform = nullptr,
    ::flatbuffers::Offset<Earthcall::Schema::PolyhedronData> polyhedron = 0,
    ::flatbuffers::Offset<Earthcall::Schema::BezierPatch> patch = 0,
    ::flatbuffers::Offset<Earthcall::Schema::SmoothSurfaceData> smooth_data = 0,
    ::flatbuffers::Offset<Earthcall::Schema::FieldData> field = 0,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::FaceTexture>> *face_textures = nullptr,
    const std::vector<Earthcall::Schema::Vec3> *face_colors = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>> *sdf_nodes = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>> *laws = nullptr,
    const char *material_id = nullptr,
    const Earthcall::Schema::Vec3 *center = nullptr,
    const Earthcall::Schema::Vec3 *authoritative_axis = nullptr,
    const Earthcall::Schema::Vec3 *target_rotation = nullptr,
    float rotation_responsiveness = 1.0f) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto transform__ = transform ? _fbb.CreateVector<float>(*transform) : 0;
  auto face_textures__ = face_textures ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::FaceTexture>>(*face_textures) : 0;
  auto face_colors__ = face_colors ? _fbb.CreateVectorOfStructs<Earthcall::Schema::Vec3>(*face_colors) : 0;
  auto sdf_nodes__ = sdf_nodes ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::SdfNode>>(*sdf_nodes) : 0;
  auto laws__ = laws ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::LawComponent>>(*laws) : 0;
  auto material_id__ = material_id ? _fbb.CreateString(material_id) : 0;
  return Earthcall::Schema::CreateEntity(
      _fbb,
      id__,
      name__,
      transform__,
      polyhedron,
      patch,
      smooth_data,
      field,
      face_textures__,
      face_colors__,
      sdf_nodes__,
      laws__,
      material_id__,
      center,
      authoritative_axis,
      target_rotation,
      rotation_responsiveness);
}

struct SaveChunk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SaveChunkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHUNK_ID = 4,
    VT_ENTITIES = 6
  };
  const ::flatbuffers::String *chunk_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHUNK_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>> *entities() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>> *>(VT_ENTITIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CHUNK_ID) &&
           verifier.VerifyString(chunk_id()) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.VerifyVectorOfTables(entities()) &&
           verifier.EndTable();
  }
};

struct SaveChunkBuilder {
  typedef SaveChunk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_chunk_id(::flatbuffers::Offset<::flatbuffers::String> chunk_id) {
    fbb_.AddOffset(SaveChunk::VT_CHUNK_ID, chunk_id);
  }
  void add_entities(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>>> entities) {
    fbb_.AddOffset(SaveChunk::VT_ENTITIES, entities);
  }
  explicit SaveChunkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SaveChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SaveChunk>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SaveChunk> CreateSaveChunk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> chunk_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Earthcall::Schema::Entity>>> entities = 0) {
  SaveChunkBuilder builder_(_fbb);
  builder_.add_entities(entities);
  builder_.add_chunk_id(chunk_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SaveChunk> CreateSaveChunkDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *chunk_id = nullptr,
    const std::vector<::flatbuffers::Offset<Earthcall::Schema::Entity>> *entities = nullptr) {
  auto chunk_id__ = chunk_id ? _fbb.CreateString(chunk_id) : 0;
  auto entities__ = entities ? _fbb.CreateVector<::flatbuffers::Offset<Earthcall::Schema::Entity>>(*entities) : 0;
  return Earthcall::Schema::CreateSaveChunk(
      _fbb,
      chunk_id__,
      entities__);
}

struct GlobalState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GlobalStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLD_NAME = 4,
    VT_TIMESTAMP = 6,
    VT_ACTIVE_LAWS = 8,
    VT_CHUNKS = 10
  };
  const ::flatbuffers::String *world_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WORLD_NAME);
  }
  const ::flatbuffers::String *timestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMESTAMP);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *active_laws() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ACTIVE_LAWS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *chunks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CHUNKS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORLD_NAME) &&
           verifier.VerifyString(world_name()) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyString(timestamp()) &&
           VerifyOffset(verifier, VT_ACTIVE_LAWS) &&
           verifier.VerifyVector(active_laws()) &&
           verifier.VerifyVectorOfStrings(active_laws()) &&
           VerifyOffset(verifier, VT_CHUNKS) &&
           verifier.VerifyVector(chunks()) &&
           verifier.VerifyVectorOfStrings(chunks()) &&
           verifier.EndTable();
  }
};

struct GlobalStateBuilder {
  typedef GlobalState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_world_name(::flatbuffers::Offset<::flatbuffers::String> world_name) {
    fbb_.AddOffset(GlobalState::VT_WORLD_NAME, world_name);
  }
  void add_timestamp(::flatbuffers::Offset<::flatbuffers::String> timestamp) {
    fbb_.AddOffset(GlobalState::VT_TIMESTAMP, timestamp);
  }
  void add_active_laws(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> active_laws) {
    fbb_.AddOffset(GlobalState::VT_ACTIVE_LAWS, active_laws);
  }
  void add_chunks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> chunks) {
    fbb_.AddOffset(GlobalState::VT_CHUNKS, chunks);
  }
  explicit GlobalStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GlobalState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GlobalState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GlobalState> CreateGlobalState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> world_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> active_laws = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> chunks = 0) {
  GlobalStateBuilder builder_(_fbb);
  builder_.add_chunks(chunks);
  builder_.add_active_laws(active_laws);
  builder_.add_timestamp(timestamp);
  builder_.add_world_name(world_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GlobalState> CreateGlobalStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *world_name = nullptr,
    const char *timestamp = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *active_laws = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *chunks = nullptr) {
  auto world_name__ = world_name ? _fbb.CreateString(world_name) : 0;
  auto timestamp__ = timestamp ? _fbb.CreateString(timestamp) : 0;
  auto active_laws__ = active_laws ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*active_laws) : 0;
  auto chunks__ = chunks ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*chunks) : 0;
  return Earthcall::Schema::CreateGlobalState(
      _fbb,
      world_name__,
      timestamp__,
      active_laws__,
      chunks__);
}

inline const Earthcall::Schema::SaveChunk *GetSaveChunk(const void *buf) {
  return ::flatbuffers::GetRoot<Earthcall::Schema::SaveChunk>(buf);
}

inline const Earthcall::Schema::SaveChunk *GetSizePrefixedSaveChunk(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Earthcall::Schema::SaveChunk>(buf);
}

template <bool B = false>
inline bool VerifySaveChunkBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Earthcall::Schema::SaveChunk>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedSaveChunkBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Earthcall::Schema::SaveChunk>(nullptr);
}

inline void FinishSaveChunkBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Earthcall::Schema::SaveChunk> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSaveChunkBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Earthcall::Schema::SaveChunk> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Schema
}  // namespace Earthcall

#endif  // FLATBUFFERS_GENERATED_EARTHCALL_EARTHCALL_SCHEMA_H_
