# CMake generated Testfile for 
# Source directory: /Users/zacharyzhang/Documents/GitHub/Earthcall
# Build directory: /Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(action_spawn_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/action_spawn_test")
set_tests_properties(action_spawn_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(basic_cube_law_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/basic_cube_law_test")
set_tests_properties(basic_cube_law_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(binary_packing_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/binary_packing_test")
set_tests_properties(binary_packing_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(change_recorder_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/change_recorder_test")
set_tests_properties(change_recorder_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(constitution_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/constitution_test")
set_tests_properties(constitution_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(continuous_law_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/continuous_law_test")
set_tests_properties(continuous_law_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(first_mover_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/first_mover_test")
set_tests_properties(first_mover_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(formation_merge_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/formation_merge_test")
set_tests_properties(formation_merge_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(formation_topology_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/formation_topology_test")
set_tests_properties(formation_topology_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(frontier_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/frontier_test")
set_tests_properties(frontier_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(geometry_cache_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/geometry_cache_test")
set_tests_properties(geometry_cache_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(glu_compat_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/glu_compat_test")
set_tests_properties(glu_compat_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(identity_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/identity_test")
set_tests_properties(identity_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(law_audit_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/law_audit_test")
set_tests_properties(law_audit_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(law_creation_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/law_creation_test")
set_tests_properties(law_creation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(law_graph_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/law_graph_test")
set_tests_properties(law_graph_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(law_loop_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/law_loop_test")
set_tests_properties(law_loop_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(law_model_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/law_model_test")
set_tests_properties(law_model_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(law_persistence_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/law_persistence_test")
set_tests_properties(law_persistence_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(logos_modality_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/logos_modality_test")
set_tests_properties(logos_modality_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(material_being_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/material_being_test")
set_tests_properties(material_being_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(material_render_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/material_render_test")
set_tests_properties(material_render_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(metalaw_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/metalaw_test")
set_tests_properties(metalaw_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(object_concept_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/object_concept_test")
set_tests_properties(object_concept_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(ontomath_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/ontomath_test")
set_tests_properties(ontomath_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(person_migration_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/person_migration_test")
set_tests_properties(person_migration_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(primitive_render_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/primitive_render_test")
set_tests_properties(primitive_render_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(property_bridge_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/property_bridge_test")
set_tests_properties(property_bridge_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(rete_compile_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/rete_compile_test")
set_tests_properties(rete_compile_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(serialization_compat_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/serialization_compat_test")
set_tests_properties(serialization_compat_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(singular_set_to_set_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/singular_set_to_set_test")
set_tests_properties(singular_set_to_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(test_field "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/test_field")
set_tests_properties(test_field PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(time_flow_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/time_flow_test")
set_tests_properties(time_flow_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(webgpu_object_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/webgpu_object_test")
set_tests_properties(webgpu_object_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(webgpu_particle_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/webgpu_particle_test")
set_tests_properties(webgpu_particle_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(webgpu_sdf_parity_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/webgpu_sdf_parity_test")
set_tests_properties(webgpu_sdf_parity_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
add_test(zone_being_test "/Users/zacharyzhang/Documents/GitHub/Earthcall/build_agy/zone_being_test")
set_tests_properties(zone_being_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;266;add_test;/Users/zacharyzhang/Documents/GitHub/Earthcall/CMakeLists.txt;0;")
subdirs("_deps/glfw-build")
subdirs("_deps/flatbuffers-build")
subdirs("_deps/websocketpp-build")
