// Corpus guard for the Material half of every committed Zone's closure.
//   Claude Code / Sonnet 5.5, session 01GxayCUN2nc7DDaeg33kXhZ, 2026-10-07.
//
// ZoneManager::prepareZoneMaterialClosure refuses to enter a Zone whose Objects
// name a Material that the Zone's own identity does not define. This test walks
// EVERY Zone identity under saves/zones with the same rule, read-only, so a
// save authored (or regenerated by a script) with a dangling Material fails CI
// here instead of silently rendering white in front of the Person.
// scripts/migrate_zone_materials.py is the repair for a failure.
//
// Rule (kept identical to the engine's on purpose):
//   resolvable = {"default"} + embedded `materials` + `materialRefs` whose
//   saves/materials/<stem>/material.json exists, validates, and carries that
//   identifier; every Object `materialId` must be in it.

#include "ConstructedBeing/Material/Material.hpp"
#include "Singularity/Storage/SaveSystem.hpp"
#include "json.hpp"

#include <filesystem>
#include <iostream>
#include <string>
#include <unordered_set>

namespace {
int checks = 0;
int failures = 0;
void check(bool ok, const std::string& message) {
    ++checks;
    if (!ok) {
        std::cout << "  FAILED: " << message << '\n';
        ++failures;
    }
}
std::string stemOf(const std::string& id) {
    static const std::string prefix = "material.";
    return id.rfind(prefix, 0) == 0 ? id.substr(prefix.size()) : id;
}
} // namespace

int main() {
    std::filesystem::path saves = "saves";
    if (!std::filesystem::exists(saves / "zones")) saves = std::filesystem::path("..") / "saves";
    saves = std::filesystem::absolute(saves);
    check(std::filesystem::exists(saves / "zones"), "saves/zones exists");
    if (!std::filesystem::exists(saves / "zones")) return 1;

    SaveSystem::setSaveRoot(saves.string());

    int zonesSeen = 0;
    for (const auto& entry : std::filesystem::directory_iterator(saves / "zones")) {
        if (!entry.is_directory()) continue;
        const std::string id = entry.path().filename().string();
        // resolveZoneIdentityPath is what the boot catalog reads: zone.ecform when
        // present, else zone.json. readZoneIdentity alone only sees .ecform.
        const std::string identityPath = SaveSystem::resolveZoneIdentityPath(id);
        std::error_code ec;
        if (identityPath.empty() || !std::filesystem::exists(identityPath, ec)) continue;
        const nlohmann::json identity = SaveSystem::readSaveData(identityPath);
        check(identity.is_object(), id + ": identity parses");
        if (!identity.is_object()) continue;
        ++zonesSeen;

        std::unordered_set<std::string> resolvable{"default"};
        if (identity.contains("materials") && identity["materials"].is_array()) {
            for (const auto& m : identity["materials"]) {
                if (m.is_object()) resolvable.insert(Material::fromJson(m).name());
            }
        }
        if (identity.contains("materialRefs")) {
            check(identity["materialRefs"].is_array(), id + ": materialRefs is an array");
            if (identity["materialRefs"].is_array()) {
                for (const auto& r : identity["materialRefs"]) {
                    const std::string ref = r.is_string() ? r.get<std::string>() : std::string{};
                    const nlohmann::json root = SaveSystem::readMaterialIdentity(ref);
                    const bool ok = root.is_object() &&
                                    stemOf(root.value("identifier", std::string{})) == stemOf(ref) &&
                                    root.contains("material") && root["material"].is_object() &&
                                    Material::fromJson(root["material"]).name() == stemOf(ref);
                    check(ok, id + ": materialRef '" + ref + "' has a valid shared root");
                    resolvable.insert(stemOf(ref));
                }
            }
        }

        const nlohmann::json* objects = nullptr;
        if (identity.contains("world") && identity["world"].is_object() &&
            identity["world"].contains("objects") && identity["world"]["objects"].is_array()) {
            objects = &identity["world"]["objects"];
        } else if (identity.contains("objects") && identity["objects"].is_array()) {
            objects = &identity["objects"];
        }
        if (!objects) continue;
        std::unordered_set<std::string> reported;
        for (const auto& o : *objects) {
            if (!o.is_object()) continue;
            const std::string mid = o.value("materialId", std::string{});
            if (mid.empty()) continue;
            const std::string s = stemOf(mid);
            if (resolvable.count(s) == 0 && reported.insert(s).second) {
                check(false, "Zone '" + id + "' names Material '" + mid +
                                 "' that its closure does not define (run scripts/migrate_zone_materials.py)");
            }
        }
    }

    check(zonesSeen > 0, "at least one Zone identity was read");
    SaveSystem::setSaveRoot("");
    std::cout << zonesSeen << " Zone identities, " << checks << " checks, " << failures << " failures\n";
    return failures == 0 ? 0 : 1;
}
